const RESET = 'APP_RESET';

/* Authentication Keys */
const LOGIN_REQUST = 'LOGIN_REQUST';
const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
const LOGIN_REQUST_ERROR = 'LOGIN_REQUST_ERROR';

/* Analytics Keys */
const STUDENT_DATA_REQUEST = 'STUDENT_DATA_REQUEST';
const STUDENT_DATA_REQUEST_SUCCESS = 'STUDENT_DATA_REQUEST_SUCCESS';
const STUDENT_DATA_REQUEST_ERROR = 'STUDENT_DATA_REQUEST_ERROR';

export default {
  LOGIN_REQUST,
  LOGIN_REQUEST_SUCCESS,
  LOGIN_REQUST_ERROR,
  STUDENT_DATA_REQUEST,
  STUDENT_DATA_REQUEST_SUCCESS,
  STUDENT_DATA_REQUEST_ERROR,
  RESET,
};